spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL}
  otp:
    email-ttl: ${OTP_EMAIL_TTL}
    password-ttl: ${OTP_PASSWORD_TTL}
    prefix:
      jwt: ${OTP_PREFIX_JWT}
      email: ${OTP_PREFIX_EMAIL}
      password: ${OTP_PREFIX_PASSWORD}

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

eureka:
  client:
    service-url.defaultZone:
      http://service-discovery:8761/eureka/
